"""Build the four 320x240 text cutscenes as direct BGR233 data."""

from __future__ import annotations

import argparse
import io
from dataclasses import dataclass
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "assets" / "source" / "cutscenes_text"
OUTPUT_DIR = ROOT / "assets" / "generated"
PREVIEW_DIR = OUTPUT_DIR / "text_cutscene_previews"
SCREEN_SIZE = (320, 240)
PAYLOAD_SIZE = SCREEN_SIZE[0] * SCREEN_SIZE[1]
SOURCE_NAMES = tuple(f"pixil-frame-{index}.png" for index in range(4))

# The supplied art has exactly these three structural colors. Mapping them
# directly avoids quantization, dithering, resizing, and any geometry change.
COLOR_MAP = {
    (0, 0, 0, 255): 0x00,       # black background
    (15, 15, 15, 255): 0x52,    # visible dark-gray frame
    (217, 217, 217, 255): 0xFF, # high-contrast light text
}


@dataclass(frozen=True)
class BuildResult:
    payloads: tuple[bytes, ...]
    files: tuple[tuple[Path, bytes], ...]


def decode_bgr233(value: int) -> tuple[int, int, int]:
    red = (value & 0x07) * 255 // 7
    green = ((value >> 3) & 0x07) * 255 // 7
    blue = ((value >> 6) & 0x03) * 255 // 3
    return red, green, blue


def convert(path: Path) -> bytes:
    with Image.open(path) as source:
        image = source.convert("RGBA")

    if image.size != SCREEN_SIZE:
        raise ValueError(
            f"{path.name}: expected {SCREEN_SIZE[0]}x{SCREEN_SIZE[1]}, "
            f"got {image.width}x{image.height}"
        )

    pixels = tuple(image.get_flattened_data())
    unexpected = sorted(set(pixels).difference(COLOR_MAP))
    if unexpected:
        raise ValueError(f"{path.name}: unexpected colors: {unexpected}")

    payload = bytes(COLOR_MAP[pixel] for pixel in pixels)
    if len(payload) != PAYLOAD_SIZE:
        raise AssertionError(f"{path.name}: expected {PAYLOAD_SIZE} bytes")
    return payload


def render_assembly(index: int, payload: bytes) -> bytes:
    lines = [
        "# Generated by tools/build_text_cutscenes_bgr233.py; do not edit.",
        "# Direct BGR233 8bpp, 320x240, row-major, no dithering.",
        f"# payload-bytes: {len(payload)}",
        "",
        ".data",
        ".align 2",
        f"text_cutscene_{index}_pixels:",
    ]
    for offset in range(0, len(payload), 32):
        chunk = payload[offset : offset + 32]
        lines.append("    .byte " + ", ".join(f"0x{value:02X}" for value in chunk))
    return ("\n".join(lines) + "\n").encode("ascii")


def render_preview(payload: bytes) -> bytes:
    rgb = [decode_bgr233(value) for value in payload]
    preview = Image.new("RGB", SCREEN_SIZE)
    preview.putdata(rgb)
    output = io.BytesIO()
    preview.save(output, format="PNG", compress_level=9, optimize=False)
    return output.getvalue()


def build(source_dir: Path = SOURCE_DIR) -> BuildResult:
    payloads = tuple(convert(source_dir / name) for name in SOURCE_NAMES)
    files: list[tuple[Path, bytes]] = []
    for index, payload in enumerate(payloads):
        files.append((OUTPUT_DIR / f"text_cutscene_{index}.data", render_assembly(index, payload)))
        files.append(
            (
                PREVIEW_DIR / f"text_cutscene_{index}_bgr233.png",
                render_preview(payload),
            )
        )
    return BuildResult(payloads=payloads, files=tuple(files))


def write_or_check(result: BuildResult, check: bool) -> bool:
    current = True
    for path, content in result.files:
        if check:
            if not path.exists() or path.read_bytes() != content:
                print(f"missing or stale: {path.relative_to(ROOT)}")
                current = False
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    return current


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    first = build()
    second = build()
    if first != second:
        raise AssertionError("text cutscene generation is not deterministic")

    return 0 if write_or_check(first, args.check) else 1


if __name__ == "__main__":
    raise SystemExit(main())
